version: "3"

services:
  pokedex-api:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/pokedex-api/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
