name: Build and Test Pokedex API
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Linter
        run: docker-compose run pokedex-api sh -c "flake8"

      - name: Run Tests
        run: docker-compose run pokedex-api sh -c "pytest"
